### ISSUE TITLE
INTERLIS Export with labels failing

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#101]
Exporting the test-dataset-DSS gives the following error (With all 3 datamodels):
![20240122_export_dss_labels_export](https://github.com/teksi/wastewater/assets/1265865/d879044f-6f72-4a06-87be-dde983ef00a8)

`Ein Fehler trat bei der Ausführung von Python-Code auf: 

AttributeError: 'InterlisExporterToIntermediateSchema' object has no attribute '_export_label_positions' 
Traceback (most recent call last):
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 474, in actionExportClicked
    self.interlisImporterExporter.action_export()
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 142, in action_export
    raise exception
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 113, in action_export
    self.interlis_importer_exporter.interlis_export(
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 157, in interlis_export
    self._export_to_intermediate_schema(
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 289, in _export_to_intermediate_schema
    twwInterlisExporter.tww_export()
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 68, in tww_export
    raise exception
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 63, in tww_export
    self._export()
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 92, in _export
    self._export_label_positions()
AttributeError: 'InterlisExporterToIntermediateSchema' object has no attribute '_export_label_positions'

Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.28.4-Firenze Firenze, fd0fb72ab3 

Python-Pfad:
C:/PROGRA~1/QGIS 3.28.4/apps/qgis-ltr/./python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins
C:/PROGRA~1/QGIS 3.28.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.28.4\bin\python39.zip
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\DLLs
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib
C:\Program Files\QGIS 3.28.4\bin
C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS 3.28.4\apps\Python39
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python
C:/Daten/QGEP/testing_dss2020
C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\gui\..\..`

**Comment by sjib** [comment]
See also https://github.com/teksi/wastewater/issues/82#issuecomment-1900204964

**Comment by cymed** [comment]
See also my review in #23, can be fixed by defining `export_label_positions()` [here](https://github.com/teksi/wastewater/blob/43e9da76c8f4ef7e5cdad409d72353cec9dea6b8/plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py#L910C35-L910C35)

**Comment by domi4484** [comment]
@sjib how should look the `t_ili_tid` for labels in the xtf? Should I use the function `tww_sys.generate_oid`?

**Comment by sjib** [comment]
> @sjib how should look the `t_ili_tid` for labels in the xtf? Should I use the function `tww_sys.generate_oid`?

@cymed Any preferences for AG64/96 compatibility?

**Comment by cymed** [comment]
I prefer t_id = t_ili_tid = obj_id on export. generate_oid is the most straightforward solution.

If we use generate_oid, we need to reset the sequence after export, otherwise we cap 1M too quickly. Automated exports are usually on a weekly basis, with i.e. 25k labels would cap after 40 weeks.
