### ISSUE TITLE
TypeError: _log() got an unexpected keyword argument 'stacklevel'

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#172]
On an Interlis Export, I got the error:

  File "%QGSPath%\profiles\tww_prod/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 386, in _export_organisation
    bemerkung=self.truncate(self.emptystr_to_null(row.remark), 80),
  File "%QGSPath%\profiles\tww_prod/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 2364, in truncate
              logger.warning(f"Value '{val}' exceeds expected length ({max_length})", stacklevel=2)
              File "C:\OSGeo4W\apps\Python39\lib\logging\__init__.py", line 1458, in warning
              self._log(WARNING, msg, args, **kwargs)
             TypeError: _log() got an unexpected keyword argument 'stacklevel'

Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.28.11-Firenze Firenze, b02458a196 
logging.__version__: 0.5.1.2

**Comment by sjib** [comment]
I get the same problem:

`Ein Fehler trat bei der Ausführung von Python-Code auf: 

TypeError: _log() got an unexpected keyword argument 'stacklevel' 
Traceback (most recent call last):
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 470, in actionExportClicked
    self.interlisImporterExporter.action_export()
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 140, in action_export
    raise exception
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 111, in action_export
    self.interlis_importer_exporter.interlis_export(
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 170, in interlis_export
    self._export_to_intermediate_schema(
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 321, in _export_to_intermediate_schema
    twwInterlisExporter.tww_export()
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 74, in tww_export
    raise exception
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 69, in tww_export
    self._export()
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 84, in _export
    self._export_sia405_abwasser()
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 150, in _export_sia405_abwasser
    self._export_organisation()
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 448, in _export_organisation
    bemerkung=self.truncate(self.emptystr_to_null(row.remark), 80),
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 2395, in truncate
    logger.warning(f"Value '{val}' exceeds expected length ({max_length})", stacklevel=2)
  File "C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\logging\__init__.py", line 1458, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'stacklevel'


Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.28.4-Firenze Firenze, fd0fb72ab3 

Python-Pfad:
C:/PROGRA~1/QGIS 3.28.4/apps/qgis-ltr/./python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins
C:/PROGRA~1/QGIS 3.28.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.28.4\bin\python39.zip
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\DLLs
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib
C:\Program Files\QGIS 3.28.4\bin
C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS 3.28.4\apps\Python39
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python
C:/Daten/QGEP/testing_dss2020/20240305
C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_testing/python/plugins\teksi_wastewater\interlis\gui\..\..
.`

**Comment by sjib** [comment]
@ponceta Can you check with opengis about this?

**Comment by domi4484** [comment]
I pushed by mistake the fix directly to main. Can someone review the changes in commit  https://github.com/teksi/wastewater/commit/c148d7bab28b8deae159c7149feb1e0c6f1e41e7?

**Comment by sjib** [comment]
@domi4484 Thanks for the fix.
I get now an error while exporting reach_progression_alternative - see https://github.com/teksi/wastewater/issues/188
Can you check on this?

**Comment by sjib** [comment]
@domi4484 And also get an error about the length of TID's for *_Text classes - see https://github.com/teksi/wastewater/issues/189
