### ISSUE TITLE
INTERLIS Export Labelexport KeyError: 'einzugsgebiet'

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#282]
Export selection to SIA405_Abwasser with all labels creates this error

```
Ein Fehler trat bei der Ausführung von Python-Code auf: 

AttributeError: einzugsgebiet 
Traceback (most recent call last):
  File "C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\util\_collections.py", line 210, in __getattr__
    return self._data[key]
KeyError: 'einzugsgebiet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 470, in actionExportClicked
    self.interlisImporterExporter.action_export()
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 141, in action_export
    raise exception
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 111, in action_export
    self.interlis_importer_exporter.interlis_export(
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 192, in interlis_export
    self._export_to_intermediate_schema(
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 383, in _export_to_intermediate_schema
    twwInterlisExporter.tww_export()
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 87, in tww_export
    raise exception
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 82, in tww_export
    self._export()
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 111, in _export
    self._export_label_positions()
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_exporter_to_intermediate_schema.py", line 3131, in _export_label_positions
    for row in self.abwasser_session.query(self.model_classes_interlis.einzugsgebiet):
  File "C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\util\_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: einzugsgebiet


Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.28.4-Firenze Firenze, fd0fb72ab3 

Python-Pfad:
C:/PROGRA~1/QGIS 3.28.4/apps/qgis-ltr/./python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python/plugins
C:/PROGRA~1/QGIS 3.28.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.28.4\bin\python39.zip
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\DLLs
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib
C:\Program Files\QGIS 3.28.4\bin
C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS 3.28.4\apps\Python39
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.28.4\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python
C:/Daten/QGEP/testing_2024.0.rc2/project-translations
C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_2024.0.rc2/python/plugins\teksi_wastewater\interlis\gui\..\..
.
```

**Comment by sjib** [comment]
![20240704_selection_label_export_key_error_einzugsgebiet](https://github.com/teksi/wastewater/assets/1265865/5c1ad5c3-ee14-4069-9738-78ebb1396327)

**Comment by sjib** [comment]
Same error with latest qgs

**Comment by sjib** [comment]
@domi4484 @cymed @urskaufmann A problem of a renaming of the layer? A language problem?

**Comment by sjib** [comment]
Export to VSA-DSS 2020 works! 
[20240704_tww-export_selection_label_all_DSS_2020_1_LV95.xtf.zip](https://github.com/user-attachments/files/16102239/20240704_tww-export_selection_label_all_DSS_2020_1_LV95.xtf.zip)

So may be we have to skip layer einzugsgebiet with SIA405_Abwasser and VSA-KEK export

**Comment by cymed** [comment]
Is already implemented in tww2ag6496
