### ISSUE TITLE
ModuleNotFoundError: No module named 'teksi_wastewater.utils.interlis' 

### ISSUE THREAD

**Issue by ponceta** [teksi/wastewater#317]
**Describe the bug**
Latest version of the plugin does not start

```
Impossible de charger l'extension 'teksi_wastewater' provoque une erreur lors de l'appel à sa méthode classFactory() 

ModuleNotFoundError: No module named 'teksi_wastewater.utils.interlis' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\__init__.py", line 27, in classFactory
    from .teksi_wastewater_plugin import TeksiWastewaterPlugin
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 49, in 
    from .utils.tww_validity_check import tww_check_oid_prefix
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\teksi_wastewater\utils\tww_validity_check.py", line 1, in 
    from .interlis.utils.various import get_pgconf_as_psycopg_dsn, logger
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'teksi_wastewater.utils.interlis'
```

**To Reproduce**
Exact steps to reproduce the behavior:
1. Download the latest plugin
2. Unzip it at the right location
3. Start QGIS and see error

**Expected behavior**
Plugin is loaded successfully

**Screenshots / data**
![image](https://github.com/user-attachments/assets/4dc04112-6235-4794-b39c-c34c90f2615a)

**Desktop (please complete the following information):**
 - TWW version
 - QGIS Version 3.34.8
 - OS 

**Additional context**

**Comment by ponceta** [comment]
Fixed by https://github.com/teksi/wastewater/commit/e7f1ca2db2402afdbe5feec9314ace42cf3116a7
