### ISSUE TITLE
Warning when identify a wastewater node

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#379]
**Describe the bug**
I get this warning: 
 WARNING    Traceback (most recent call last):
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\linking_relation_editor\gui\linking_relation_editor_widget.py", line 774, in afterSetRelations
              self._checkTransactionGroup()
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\linking_relation_editor\gui\linking_relation_editor_widget.py", line 788, in _checkTransactionGroup
              connectionString = PluginHelper.connectionString(self.relation().referencedLayer().source())
             AttributeError: 'NoneType' object has no attribute 'source'

**To Reproduce**
Exact steps to reproduce the behavior:
1. Select 'vw_wastewater_node' (Editing status does not matter)
2. Choose 'Identify Features' tool
3. Click on a wastewater node
4. See warning

Same behaviour when click on the Wastewater Nodes Tab in vw_tww_wastewater_structure

**Expected behavior**

**Screenshots / data**
-

**Desktop (please complete the following information):**
 - TWW version 0.0.0 
 - QGIS Version 3.34.4
 - OS Win 10

**Additional context**
-

**Comment by cymed** [comment]
Looks like there is a problem with the linking relation editor plugin. What version do you use?

**Comment by urskaufmann** [comment]
Linking Relation Editor

Provides a relation editor widget with an alternative link child dialog

Provides a relation editor widget with an alternative link child dialog

4 rating vote(s), 14834 downloads
Category	Vector
Tags	relation
More info	homepage   bug tracker   code repository
Author	OPENGIS.ch
Installed version	1.3.0
Available version (stable)	v1.3.0 updated at 22.03.2024 11:08

**Comment by domi4484** [comment]
In QGIS, when we delete (maybe as well rename?) a relation, the corresponding relation editor widgets are not removed from the attribute forms. This is probably what happened with a relation in the table `vw_tww_overflow`. The relation editor widget seems configured with a non-existing relation (empty string). 
@urskaufmann should be `trottle_shut off unit-overflow`?

![image](https://github.com/user-attachments/assets/df95e8cc-b186-417a-aa92-1ca8be5df67f)

I made a pull request for the Linking relation editor to not show a python exception but log a little more explicative warning https://github.com/opengisch/qgis-linking-relation-editor/pull/51

Still this kind of issue can be hard to find. It would be good to find a solution in QGIS to warn the user about such kind of misconfiguration

**Comment by domi4484** [comment]
@ponceta maybe in the similar direction of https://github.com/qgis/QGIS/issues/58973 we could propose to add a warning icon o something visual in the column `Form Layout` to indicate when an editor widget is configured for a no-more-existing field or a relation editor is configured for a no-more-existing relation

**Comment by ponceta** [comment]
See the request QGIS Side : https://github.com/qgis/QGIS/issues/59001

**Comment by ponceta** [comment]
I have no such warning on https://github.com/teksi/wastewater/pull/464

**Comment by urskaufmann** [comment]
This empty line still exists in the TWW-project 2024.0.5 (and there is still this error). TWW-project has to be corrected

**Comment by gacarrillor** [comment]
> [@ponceta](https://github.com/ponceta) maybe in the similar direction of [qgis/QGIS#58973](https://github.com/qgis/QGIS/issues/58973) we could propose to add a warning icon o something visual in the column `Form Layout` to indicate when an editor widget is configured for a no-more-existing field or a relation editor is configured for a no-more-existing relation

FYI, this QGIS PR https://github.com/qgis/QGIS/pull/61544 will make orphan fields stand out (in red color), as relations did after https://github.com/qgis/QGIS/pull/59654.

**Comment by cymed** [comment]
I think this is fixed, reopen if needed
