### ISSUE TITLE
TWW 2024.0.2: sqlalchemy 1.4 necessary for import/export, is not documented

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#439]
**Describe the bug**
Installed the version 2024.0.2: Plugin, database and project. I'm not able to import the vsa_organisationen_2020_1.xtf

Get this error:
An error has occurred while executing Python code: 

AttributeError: 'Session' object has no attribute 'get' 
Traceback (most recent call last):
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 612, in actionImportClicked
    self.interlisImporterExporter.action_import()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 79, in action_import
    raise exception
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 60, in action_import
    self.interlis_importer_exporter.interlis_import(
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 148, in interlis_import
    raise exception
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 106, in interlis_import
    tww_session = self._import_from_intermediate_schema(import_model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 261, in _import_from_intermediate_schema
    interlisImporterToIntermediateSchema.tww_import(skip_closing_tww_session=True)
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_importer_to_intermediate_schema.py", line 41, in tww_import
    raise exception
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_importer_to_intermediate_schema.py", line 33, in tww_import
    self._tww_import(skip_closing_tww_session)
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_importer_to_intermediate_schema.py", line 66, in _tww_import
    self._import_sia405_abwasser()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_importer_to_intermediate_schema.py", line 78, in _import_sia405_abwasser
    self._import_organisation()
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_importer_to_intermediate_schema.py", line 654, in _import_organisation
    organisation = self.create_or_update(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\interlis_model_mapping\interlis_importer_to_intermediate_schema.py", line 435, in create_or_update
    instance = self.session_tww.get(cls, obj_id)
               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute 'get'

Python version: 3.12.6 (main, Sep  7 2024, 18:59:42) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.10-Prizren Prizren, 113de9e1 

Python Path:
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins
C:/PROGRA~1/QGIS3/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3\apps\grass\grass84\etc\python
C:\Windows\system32
C:\Program Files\QGIS3\bin\python312.zip
C:\PROGRA~1\QGIS3\apps\Python312\DLLs
C:\PROGRA~1\QGIS3\apps\Python312\Lib
C:\Program Files\QGIS3\bin
C:\PROGRA~1\QGIS3\apps\Python312
C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python
.
T:/12_GIS/01_QGIS/QGEP/qgep-test/tww_project_2020/project 2024-09-30
C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\teksi_wastewater\interlis\gui\..\..

**Desktop (please complete the following information):**
 - TWW version 2024.0.2
 - QGIS Version 3.34.10
 - OS Win10

**Comment by urskaufmann** [comment]
I did then import the vsa_test_data with my bat-files, this worked

**Comment by domi4484** [comment]
@urskaufmann Can you open a python console in QGIS and post the version of sqlalchemy?
```python
import sqlalchemy
sqlalchemy.__version__
```

Can you also show you bat file?

**Comment by urskaufmann** [comment]
import sqlalchemy
sqlalchemy.__version__
'1.3.24'

bat-files: that are many sql (originally created from @sjib for qgep, usind also ili2pg) to create a schema and in a second step to import the data

**Comment by urskaufmann** [comment]
so we have to update the doc?

There is actually:  pip3 install "sqlalchemy~=1.3.22" "geoalchemy2>=0.9.0"

**Comment by ponceta** [comment]
> so we have to update the doc?
> 
> There is actually: pip3 install "sqlalchemy~=1.3.22" "geoalchemy2>=0.9.0"

And add it to the python requirements to get an issue when librairies are not up to date.

**Comment by urskaufmann** [comment]
With sqlalchemy > 1.4 it works.

Imo is import and export one of the main-functions. It can not be, that I have to install something additional to the standard tww-installation to be able to import or export. Therefor these installation-instructions should be in the installation-guide...

**Comment by domi4484** [comment]
In the past we packaged some python modules directly into a plugin. But that's doesn't work for every module. We could check if its possible for sqlalchemy/geoalchemy
