### ISSUE TITLE
Network following crashing when levels are missing

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#476]
**Describe the bug**

When selecting network following upstream on node V1.102 a python error appears and cursors keep turning (blue circle). Difficult to work on. 

**To Reproduce**
Exact steps to reproduce the behavior:

**Expected behavior**
_A clear and concise description of what you expected to happen._

No half crash if using network following function

**Screenshots / data**
If applicable, add screenshots or data to help explain your problem.
![grafik](https://github.com/user-attachments/assets/94ade8e6-72db-49bc-bfad-a370fc02c2e5)

```
2024-10-28T11:59:34     WARNING    Traceback (most recent call last):
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwmaptools.py", line 145, in canvasReleaseEvent
              self.leftClicked(event)
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwmaptools.py", line 559, in leftClicked
              self.getTree(match.featureId())
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwmaptools.py", line 508, in getTree
              nodes, edges = self.network_analyzer.getTree(node_id, upstream)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 298, in getTree
              pred, _ = nx.bellman_ford_predecessor_and_distance(my_graph, node)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS 3.34.8\apps\Python312\Lib\site-packages\networkx\utils\decorators.py", line 789, in func
              return argmap._lazy_compile(__wrapper)(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File " compilation 4", line 3, in argmap_bellman_ford_predecessor_and_distance_1
              import gzip
              ^^^^
              File "C:\PROGRA~1\QGIS 3.34.8\apps\Python312\Lib\site-packages\networkx\utils\backends.py", line 633, in __call__
              return self.orig_func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS 3.34.8\apps\Python312\Lib\site-packages\networkx\algorithms\shortest_paths\weighted.py", line 1246, in bellman_ford_predecessor_and_distance
              raise nx.NodeNotFound(f"Node {source} is not found in the graph")
             networkx.exception.NodeNotFound: Node 82 is not found in the graph
             
2024-10-28T12:00:43     WARNING    Traceback (most recent call last):
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwmaptools.py", line 145, in canvasReleaseEvent
              self.leftClicked(event)
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwmaptools.py", line 559, in leftClicked
              self.getTree(match.featureId())
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwmaptools.py", line 508, in getTree
              nodes, edges = self.network_analyzer.getTree(node_id, upstream)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\tww_pre_202403/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 298, in getTree
              pred, _ = nx.bellman_ford_predecessor_and_distance(my_graph, node)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File " compilation 4", line 3, in argmap_bellman_ford_predecessor_and_distance_1
              import gzip
              ^^^^
              File "C:\PROGRA~1\QGIS 3.34.8\apps\Python312\Lib\site-packages\networkx\utils\backends.py", line 633, in __call__
              return self.orig_func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS 3.34.8\apps\Python312\Lib\site-packages\networkx\algorithms\shortest_paths\weighted.py", line 1246, in bellman_ford_predecessor_and_distance
              raise nx.NodeNotFound(f"Node {source} is not found in the graph")
             networkx.exception.NodeNotFound: Node 82 is not found in the graph

```             

**Desktop (please complete the following information):**
 - TWW version 2024.0.3
 - QGIS Version 3.34.8
 - OS Win 10

**Additional context**

Looks like levels (cote attributes) are missing in this part of (secondary) network

**Comment by sjib** [comment]
No cover level
![grafik](https://github.com/user-attachments/assets/ec07b091-c1e4-491b-9914-4e388e838105)

**Comment by sjib** [comment]
Bottom level exists:
![grafik](https://github.com/user-attachments/assets/20f0db11-2796-4395-b3a2-7da0892ea5a5)
