### ISSUE TITLE
vw_tww_overflow: symbol jumps and python-error

### ISSUE THREAD

**Issue by urskaufmann** [teksi/wastewater#479]
**Describe the bug**
The symbol of the overflows is not helpful. The curve is nice, but the point symbol is not at the place, where the overflow is and it happens, that the point symbol jumps of the zoom changes.
If I open the attribute table, I get python-errors.

**To Reproduce**
Exact steps to reproduce the behavior:
1. New TWW installation Release 2024.03
2. Go to one of the overflows, zoom in and out (often it's without jump, sometimes the point symbol jumps)
3. open the attribute table of vw_tww_overflow

**Screenshots / data**
![image](https://github.com/user-attachments/assets/3a492269-7b1a-4139-aa87-8c7b3bfdf99e)
1:39, Symbol in the right side

![image](https://github.com/user-attachments/assets/077e27ae-f14a-423f-8759-2e56efa65172)
1:31, Symbol in the left side

![image](https://github.com/user-attachments/assets/fd0730a5-5f36-4c29-9b05-9024a7f8fa17)
1:16, Symbol on the other side

![image](https://github.com/user-attachments/assets/559f0157-e6d0-4dbe-b6a1-2eea18ff3bf0)
Attribute table open -> python error

**Desktop (please complete the following information):**
 - TWW version 2024.03
 - QGIS Version 3.34.10
 - OS Win 10

**Comment by ponceta** [comment]
I can't reproduce the error you mention, at least on https://github.com/teksi/wastewater/releases/tag/2024.0.4

Can you try it on the base project (english), I suspect a translation error bringing some strange behaviour

![vw_overflows](https://github.com/user-attachments/assets/98ff72f3-cca9-42d1-a45b-4f7ff2f5d236)

**Comment by urskaufmann** [comment]
Its still jumping in de and in en-project. I can reproduce on manhole 1.001 in the vsa-muster-data. When changing scale from 1:15 -> 1:30 -> 1:60. May be its a conflict with the manhole-labels.
What's not good: to get the overflow, you can not click on the pointsymbol, you have to click on the startpoint of the line. And if I click there with the identify feature-tool, I get again this python-error:
An error has occurred while executing Python code: See message log (Python Error) for more details.

2024-11-27T10:15:09     WARNING    Traceback (most recent call last):
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\linking_relation_editor\gui\linking_relation_editor_widget.py", line 777, in afterSetRelations
              self._checkTransactionGroup()
              File "C:\Users/KAU/AppData/Roaming/QGIS/QGIS3\profiles\tww_test/python/plugins\linking_relation_editor\gui\linking_relation_editor_widget.py", line 791, in _checkTransactionGroup
              connectionString = PluginHelper.connectionString(self.relation().referencedLayer().source())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: 'NoneType' object has no attribute 'source'
