### ISSUE TITLE
JavaNotFoundErro -> Missing java on computer

### ISSUE THREAD

**Issue by sjib** [teksi/wastewater#503]
The following error gives a hint, that no Java (JRE) is installed on the computer:
```
2024-12-03T16:57:22     WARNING    Traceback (most recent call last):
              File "C:\Users/kay.korrodi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 598, in actionExportClicked
              self.interlisImporterExporter = InterlisImporterExporterGui()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/kay.korrodi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 27, in __init__
              self.interlis_importer_exporter = InterlisImporterExporter(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/kay.korrodi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 43, in __init__
              self.interlisTools = InterlisTools()
              ^^^^^^^^^^^^^^^
              File "C:\Users/kay.korrodi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\utils\
ili2db.py
", line 22, in __init__
              self.java_executable_path = ili2dbutils.get_java_path(BaseConfiguration())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/kay.korrodi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\libs\modelbaker\iliwrapper\
ili2dbutils.py
", line 262, in get_java_path
              raise JavaNotFoundError(version_output)
             teksi_wastewater.libs.modelbaker.iliwrapper.ili2dbutils.JavaNotFoundError 
Add any other context about the problem here.

```

**Comment by ponceta** [comment]
Has the JAVA installation been performed?

https://github.com/teksi/wastewater/pull/504/files#diff-ed45510a571e8848bb5402c279e95874a8a19b9560f01a845bd5ee61987c8647L26

**Comment by sjib** [comment]
Yes. 

Maybe the error message itself could be improved.
