### ISSUE TITLE
fe_sendauth: no password supplied 

### ISSUE THREAD

**Issue by Kay-Korrodi** [teksi/wastewater#505]
**Describe the bug**
On exporting INTERLIS I get the following authentication error

**To Reproduce**
Exact steps to reproduce the behavior:
1. Go to 'INTERLIS export'
2. Select 'SIA405 Abwasser 2020.1'
3. Click on export

**Expected behavior**

Also with database on server pg_conf setting should be read correctly

**Screenshots / data**
Ein Fehler trat bei der Ausführung von Python-Code auf: 
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied 
Traceback (most recent call last):
  File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 619, in actionExportClicked
    self.interlisImporterExporter.action_export()
  File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 149, in action_export
    raise exception
  File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 119, in action_export
    self.interlis_importer_exporter.interlis_export(
  File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 168, in interlis_export
    self._check_subclass_counts(limit_to_selection)
  File "C:\Users/xxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 488, in _check_subclass_counts
    self._check_subclass_count(
  File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 563, in _check_subclass_count
    with DatabaseUtils.PsycopgConnection() as connection:
  File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\utils\database_utils.py", line 39, in __enter__
    self.connection = psycopg.connect(
                      ^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied

Python-Version: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.34.8-Prizren Prizren, 91642333 
Python-Pfad:
•	C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\generate_swmm_inp
•	C:/PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python
•	C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS33~1.8/apps/qgis-ltr/./python/plugins
•	C:\PROGRA~1\QGIS33~1.8\apps\grass\grass83\etc\python
•	C:\Users\Default\Documents
•	C:\Program Files\QGIS 3.34.8\bin\python312.zip
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312\DLLs
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib
•	C:\Program Files\QGIS 3.34.8\bin
•	C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib\site-packages
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib\site-packages\win32
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS33~1.8\apps\Python312\Lib\site-packages\Pythonwin
•	C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	X:/QGIS/TWW/project-translations
•	C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\gui\..\..

**Desktop (please complete the following information):**
 - TWW version 2024.0.4 
 - QGIS Version 3.34.8
 - OS Win 11

**Additional context**

**Comment by sjib** [comment]
Maybe connected to <https://github.com/opengisch/QgisModelBaker/issues/996#event-15509198892>

**Comment by ponceta** [comment]
Is your tww project opening correctly?

Could you check your pg_tww settings configuration? Is there a password provided in your pg_service file?

**Comment by Kay-Korrodi** [comment]
Thanks for your feedback.

Stefan and i tried it together yes my project is correctly

pg_service is also working well with pw and stuff like that

we have a cloud server and somehoe it goes over the localhost as you can see in the message.

i hope my answer helps

**Comment by Kay-Korrodi** [comment]
Good News
With the Teksi Plugin from 01.11.24 i can make xtf's so i think the new version of the blugin does not work anymore....
Also de phyton errors about the reach_points is somehow with this version gone...

**Comment by Kay-Korrodi** [comment]
Sad News
Another Person that i know installed the latest Plugin from github and had the same error as i had. So it is not only on my computer. Maybe this helps to find the bug.

**Comment by ponceta** [comment]
- [ ] Is your password in the pg file? In a pg pass? 

- [ ] could you try defining the host as 127.0.0.1 instead of localhost?

**Comment by Kay-Korrodi** [comment]
our pgpass file is filled with the ip off our server and the dbases from there
i cant change the localhost because i dont have one in my pgpass we have there our ip from our server i can send you my pgpass via mail if needed
as i wrote befor if i us an older teksi plugin it works. so it must be new version of the plugin

**Comment by cymed** [comment]
I suppose that error is linked with #430 
In order to allow using sslparams, we now pass all pgconf params in https://github.com/teksi/wastewater/blob/5cdd61e9ee6481dac2dd5c72a067c952715f07d5/plugin/teksi_wastewater/utils/database_utils.py#L130
Change from https://github.com/teksi/wastewater/commit/5cdd61e9ee6481dac2dd5c72a067c952715f07d5

**Comment by sjib** [comment]
@ponceta @cymed Looks like a critical error - how can we fix this for release 2024.0

**Comment by Kay-Korrodi** [comment]
1. the current did not work the one we use is dated on 01.11.24  i dont know wich version it is i can send it to you if needed
2. # zermatt_prod 🦣☁️
[zermatt_prod]
host=xxx.xxx.xxx.xx
port=xxxx
dbname=xxx
user=postgres
password=xxx
3. locally
4. no remot server

i know a company trying tww and they had the same problem i sent em the older version (the one we use from point 1) of the teksi modul and it works there too so it cant be my configuration...

**Comment by cymed** [comment]
@Kay-Korrodi can you apply the changes in #511 and set the logging level to 'debug'? Best case we log the connection it creates for you.

**Comment by sjib** [comment]
Documentation see https://github.com/teksi/wastewater/pull/511#issuecomment-2557189770

**Comment by Kay-Korrodi** [comment]
Good Morning my Friends from TEKSI

We gave 2024.0.5 a try on our brand new server. i just want to inform you, that we still get the localhost error. Do you think we get a fix in the next time 👍 it is now difficult to make exports, because a lot changed till the last working version...

**Comment by cymed** [comment]
Did you create a debug log for us? If no - in the TWW settings, go to "Developer options", set the log level to "Debug" and log to a file

**Comment by Kay-Korrodi** [comment]
@taetscher Thank you for the log. I look forward to the working tool 😄

**Comment by cymed** [comment]
The pg_service is loaded on https://github.com/teksi/wastewater/blob/main/plugin/teksi_wastewater/teksi_wastewater_plugin.py#L672-L689

**Comment by sjib** [comment]
@sjib to check with Zermatt whether it is solved or not

**Comment by cymed** [comment]
Going through the log of @taetscher I see the following:

- there is no debug log for `PG_CONFIG_PATH`. This means that [read_pgservice](https://github.com/teksi/wastewater/blob/main/plugin/teksi_wastewater/utils/database_utils.py#L83) is not called. 
- As the psycopg dsn is logged, we do enter [get_pgconf_as_psycopg_dsn](https://github.com/teksi/wastewater/blob/main/plugin/teksi_wastewater/utils/database_utils.py#L134)
- The db connection is configured [here](https://github.com/teksi/wastewater/blob/main/plugin/teksi_wastewater/teksi_wastewater_plugin.py#L672) if the [layers are available](https://github.com/teksi/wastewater/blob/main/plugin/teksi_wastewater/teksi_wastewater_plugin.py#L450) which is linked to the network_layer_notifier. 

Next steps:

- Check if there is a misnomer in the tww project (QGIS Layer id of vw_tww_wastewater_structure)
- add a debug point to [onLayersAvailable](https://github.com/teksi/wastewater/blob/main/plugin/teksi_wastewater/teksi_wastewater_plugin.py#L450)

**Comment by sjib** [comment]
@taetscher @Kay-Korrodi 
At startup of the project this should be logged in the tww tab:
```
2025-02-13T10:20:18        teksi_wastewater:TEKSI Wastewater plugin version 2024.0.5 started
2025-02-13T10:20:18        teksi_wastewater.utils.translation:Using system default locale: de_CH
2025-02-13T10:21:04        teksi_wastewater.utils:Checking setup of oid prefix
2025-02-13T10:21:04        teksi_wastewater.utils:PGSYSCONFDIR: C:\..\..\pgconf\pg_service.conf
2025-02-13T10:21:04        teksi_wastewater.utils:psycopg dsn: host=localhost port=5433 dbname=tww user=xxx password=[PASSWORD]
2025-02-13T10:21:04        teksi_wastewater.utils:Checking setup of default_values
2025-02-13T10:21:04        teksi_wastewater.utils:PGSYSCONFDIR: C:\..\..\pgconf\pg_service.conf
2025-02-13T10:21:04        teksi_wastewater.utils:psycopg dsn: host=localhost port=5433 dbname=tww user=xxx password=[PASSWORD]
2025-02-13T10:21:04        teksi_wastewater.utils:Check symbology triggers enabled
2025-02-13T10:21:04        teksi_wastewater.utils:PGSYSCONFDIR: C:\..\..\pgconf\pg_service.conf
2025-02-13T10:21:04        teksi_wastewater.utils:psycopg dsn: host=localhost port=5433 dbname=tww user=xxx password=[PASSWORD]
```
Does this work correctly?

And this should be logged while exporting to INTERLIS:
```
2025-02-13T10:27:38        teksi_wastewater.utils:INTEGRITY CHECK wastewater_networkelement subclass data...
2025-02-13T10:27:38        teksi_wastewater.utils:CONNECTING TO DATABASE...
2025-02-13T10:27:38        teksi_wastewater.utils:PGSYSCONFDIR: C:\..\..\pgconf\pg_service.conf
2025-02-13T10:27:38        teksi_wastewater.utils:psycopg dsn: host=localhost port=5433 dbname=tww user=xxx password=[PASSWORD]
2025-02-13T10:27:38        teksi_wastewater.utils:Number of wastewater_networkelement datasets: 55581
2025-02-13T10:27:38        teksi_wastewater.utils:Number of reach datasets: 32995
2025-02-13T10:27:38        teksi_wastewater.utils:Number of wastewater_node datasets: 22586
2025-02-13T10:27:38        teksi_wastewater.utils:OK: number of subclass elements of class wastewater_networkelement OK in schema tww_od!
2025-02-13T10:27:38        teksi_wastewater.utils:INTEGRITY CHECK wastewater_structure subclass data...
etc.
```

I don't see anyl line that references to pg_service.conf in your log. Did you set that path?
Documentation how to setup see 
Windows: https://teksi.github.io/wastewater/installation-guide/workstation.html#windows-pg-service
Linux/MacOS: https://teksi.github.io/wastewater/installation-guide/workstation.html#linux-macos-pg-service

**Comment by Kay-Korrodi** [comment]
Thanks for your Message. on 19th Dezember i answered that the pg_service.conf is set. i know at least another company not only Zermatt and Ryser that get this error. And i know all have set the pg_service.conf.... especially because i set it up for that company and  when they swap to the old version i use they dont have that error anymore. i am 100% sure that it is the tool and not the setup of our computers....
maybe @taetscher can send the log to you i only run the old version of the tool. Because that version runs perfectly fine😄

**Comment by taetscher** [comment]
@sjib 
Wherever it says `{redacted :)}`, I went ahead and left out some semi-sensitive information. I did however, make sure that the information in the original logs checks out.

On startup I get 

```
2025-02-13T12:46:10        teksi_wastewater:TEKSI Wastewater plugin version 2024.0.5 started
2025-02-13T12:46:10        teksi_wastewater.utils.translation:Using QGIS override locale: en_US
```

in the log messages tww-tab

On export to INTERLIS I get 

```
2025-02-13T12:53:17        teksi_wastewater.utils:INTEGRITY CHECK wastewater_networkelement subclass data...
2025-02-13T12:53:17        teksi_wastewater.utils:CONNECTING TO DATABASE...
2025-02-13T12:53:17        teksi_wastewater.utils:psycopg dsn: 
```

as well as 

<details>
  <summary>This psycopg2 error</summary>
  
  ```py
2025-02-13T12:53:21     WARNING    Traceback (most recent call last):
              File "{redacted :)}/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 630, in actionExportClicked
              self.interlisImporterExporter.action_export()
              File "{redacted :)}/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 149, in action_export
              raise exception
              File "{redacted :)}/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\gui\interlis_importer_exporter_gui.py", line 119, in action_export
              self.interlis_importer_exporter.interlis_export(
              File "{redacted :)}/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 168, in interlis_export
              self._check_subclass_counts(limit_to_selection)
              File "{redacted :)}/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 488, in _check_subclass_counts
              self._check_subclass_count(
              File "{redacted :)}/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\interlis\interlis_importer_exporter.py", line 563, in _check_subclass_count
              with DatabaseUtils.PsycopgConnection() as connection:
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "{redacted :)}/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\utils\database_utils.py", line 40, in __enter__
              self.connection = psycopg.connect(
              ^^^^^^^^^^^^^^^^
              File "{redacted :)}\AppData\Roaming\Python\Python312\site-packages\psycopg2\__init__.py", line 122, in connect
              conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
```
</details>



In the python log messages tab.

However, the server I am trying to connect to is not running on localhost. Connecting to the remote instance via QGIS and PgAdmin works just fine (using the service-definition), which means the server is reachable by our system. It's just the INTERLIS-Export that seems to get the impression that the connection is pointing to a localhost somehow.

Only when i hardcode the `PGSERVICE` Attribute of the DatabaseConfig Class to the name of my service definition, do I get the 

<details>
  <summary>same log messages as you do and the export works (taken from the logfile so I didn't have to wait for the export to finish).</summary>
  
  ```py
2025-02-13 12:48:14,558:INFO:plugin_utils:INTEGRITY CHECK wastewater_networkelement subclass data...
2025-02-13 12:48:14,559:INFO:plugin_utils:CONNECTING TO DATABASE...
2025-02-13 12:48:14,560:DEBUG:plugin_utils:PGSYSCONFDIR:  {redacted :)}\custom_env_variables_BES\postgres\pg_service.conf
2025-02-13 12:48:14,562:DEBUG:plugin_utils:psycopg dsn: host={redacted :)} port=5432 dbname={redacted :)} user={redacted :)} password=[PASSWORD]
2025-02-13 12:48:14,727:INFO:plugin_utils:Number of wastewater_networkelement datasets: 7857
2025-02-13 12:48:14,747:INFO:plugin_utils:Number of reach datasets: 4959
2025-02-13 12:48:14,765:INFO:plugin_utils:Number of wastewater_node datasets: 2898
2025-02-13 12:48:14,766:INFO:plugin_utils:OK: number of subclass elements of class wastewater_networkelement OK in schema tww_od!
2025-02-13 12:48:14,768:INFO:plugin_utils:INTEGRITY CHECK wastewater_structure subclass data...
...
```
</details>

---

env-var is set, pointing to the directory where my `pg_service.conf` file is located:

![Image](https://github.com/user-attachments/assets/58fe9c63-2794-422d-8ea6-35808b337529)

**Comment by cymed** [comment]
Do the other plugin buttons work?

**Comment by cymed** [comment]
@taetscher The plugin ought to load the service from the layer definition of vw_tww_wastewater_structure. Can you verify that there is no (ghost) layer with another datasource in the project?

**Comment by taetscher** [comment]
@cymed I checked, did not find any "ghost" layer. There are, however, some layers within the project that use different service-defs (getting tables from different databases).

**Comment by cymed** [comment]
@taetscher does the additional log in #548 return a postgres layer?

**Comment by taetscher** [comment]
@cymed 

I also tested using the current .qgs file - to no avail.
Then I tried disabling/re-enabling the TEKSI-Plugin in QGIS Plugin Manager.

This yielded an interesting error-message (one that I think I saw a couple of times before - sometimes it would show up, sometimes, it wouldn't):

```python
ValueError: No Point Geometry found for Node ch19qnvg1kA1FnTa (Type: reach_point) 
Traceback (most recent call last):
  File "{redacted :)}AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 112, in _addVertices
    vertex = feat.geometry().asPoint()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Null geometry cannot be converted to a point.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "{redacted :)}AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 457, in onLayersAvailable
    self.network_analyzer.setNodeLayer(layers["vw_network_node"])
  File "{redacted :)}AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 94, in setNodeLayer
    self.createGraph()
  File "{redacted :)}AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 219, in createGraph
    self._addVertices()
  File "{redacted :)}AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 114, in _addVertices
    raise ValueError(f"No Point Geometry found for Node {obj_id} (Type: {obj_type})")
ValueError: No Point Geometry found for Node ch19qnvg1kA1FnTa (Type: reach_point)
```

What I find rather odd is that:

```SQL
SELECT * FROM tww_od.reach_point
WHERE situation3d_geometry IS NULL
ORDER BY obj_id ASC 
```
Yields nothing, there are no reach points that are missing a geometry...

 I somehow doubt this has anything to do with this issue, though.

**Comment by cymed** [comment]
> @cymed 
> 
> I also tested using the current .qgs file - to no avail.
> Then I tried disabling/re-enabling the TEKSI-Plugin in QGIS Plugin Manager.
> 
> This yielded an interesting error-message (one that I think I saw a couple of times before - sometimes it would show up, sometimes, it wouldn't):
> 
> ```python
> ValueError: No Point Geometry found for Node ch19qnvg1kA1FnTa (Type: reach_point) 
> Traceback (most recent call last):
>   File "{redacted :)}AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 112, in _addVertices
>     vertex = feat.geometry().asPoint()
>              ^^^^^^^^^^^^^^^^^^^^^^^^^
> ValueError: Null geometry cannot be converted to a point.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "{redacted :)}AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\teksi_wastewater_plugin.py", line 457, in onLayersAvailable
>     self.network_analyzer.setNodeLayer(layers["vw_network_node"])
>   File "{redacted :)}AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 94, in setNodeLayer
>     self.createGraph()
>   File "{redacted :)}AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 219, in createGraph
>     self._addVertices()
>   File "{redacted :)}AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 114, in _addVertices
>     raise ValueError(f"No Point Geometry found for Node {obj_id} (Type: {obj_type})")
> ValueError: No Point Geometry found for Node ch19qnvg1kA1FnTa (Type: reach_point)
> ```
> 
> What I find rather odd is that:
> 
> ```SQL
> SELECT * FROM tww_od.reach_point
> WHERE situation3d_geometry IS NULL
> ORDER BY obj_id ASC 
> ```
> Yields nothing, there are no reach points that are missing a geometry...
> 
>  I somehow doubt this has anything to do with this issue, though.
> 

setNodeLayer is fired in the same function that fires loading the connection data from  vw_tww_wastewater_structure, so there might be a connection. 

vw_network_node is a materialized view, so there could be a NULL geometry that's fixed in the meantime

**Comment by taetscher** [comment]
@cymed 

> setNodeLayer is fired in the same function that fires loading the connection data from vw_tww_wastewater_structure, so there might be a connection.

I see.
Interesting thing about this: I could swear I did not get this error every time I loaded the qgis project...? But that could also be observer bias.

> vw_network_node is a materialized view, so there could be a NULL geometry that's fixed in the meantime

Bingo!
After manually refreshing the matview, I now get the following logged:

```python
2025-02-21T07:54:05        teksi_wastewater:TEKSI Wastewater plugin version 0.0.0 started
2025-02-21T07:54:05        teksi_wastewater.utils.translation:Using QGIS override locale: en_US
2025-02-21T07:54:37        teksi_wastewater:dataprovider of vw_tww_wastewater_structure: 
2025-02-21T07:54:37        teksi_wastewater.utils:Checking setup of oid prefix
2025-02-21T07:54:37        teksi_wastewater.utils:PGSYSCONFDIR: {redacted :)}\custom_env_variables_BES\postgres\pg_service.conf
2025-02-21T07:54:37        teksi_wastewater.utils:psycopg dsn: host={redacted :)} port=5432 dbname={redacted :)} user={redacted :)} password=[PASSWORD]
2025-02-21T07:54:37        teksi_wastewater.utils:Checking setup of default_values
2025-02-21T07:54:37        teksi_wastewater.utils:PGSYSCONFDIR: {redacted :)}\custom_env_variables_BES\postgres\pg_service.conf
2025-02-21T07:54:37        teksi_wastewater.utils:psycopg dsn: host={redacted :)} port=5432 dbname={redacted :)} user={redacted :)} password=[PASSWORD]
2025-02-21T07:54:37        teksi_wastewater.utils:Check symbology triggers enabled
2025-02-21T07:54:37        teksi_wastewater.utils:PGSYSCONFDIR: {redacted :)}\custom_env_variables_BES\postgres\pg_service.conf
2025-02-21T07:54:37        teksi_wastewater.utils:psycopg dsn: host={redacted :)} port=5432 dbname={redacted :)} user={redacted :)} password=[PASSWORD]
```

The INTERLIS-Export now also knows where to look for the data.
Thanks a lot for your support!

@Kay-Korrodi FYI

**Comment by sjib** [comment]
So what is the conclusion of all these findings?

- Should we add a refreshing of the materialized views before running INTERLIS export?
- any other suggestions?

**Comment by cymed** [comment]
My conclusion is to check the tww layers separately from the network views to ensure we get the correct pg_service even if the materialized views have problems. See. #551

**Comment by sjib** [comment]
@taetscher So can this be closed?

**Comment by sjib** [comment]
I will close - else please re-open and we move to 2024.1 Milestones
