### ISSUE TITLE
ProfileTool Error

### ISSUE THREAD

**Issue by cymed** [teksi/wastewater#91]
**Describe the bug**
Profile tool crashes with a TypeError (see below). 

**To Reproduce**
Exact steps to reproduce the behavior:
1. Use profile tool
2. . See error

**Expected behavior**

**Screenshots / data**
Traceback (most recent call last):
  File "C:\Users/%usr%/AppData/Roaming/QGIS/QGIS3\profiles\tww_dev/python/plugins\teksi_wastewater\tools\twwmaptools.py", line 145, in canvasReleaseEvent
    self.leftClicked(event)
  File "C:\Users/%usr%/AppData/Roaming/QGIS/QGIS3\profiles\tww_dev/python/plugins\teksi_wastewater\tools\twwmaptools.py", line 468, in leftClicked
    pf = self.findPath(self.selectedPathPoints[-1][0], match.featureId())
  File "C:\Users/%usr%/AppData/Roaming/QGIS/QGIS3\profiles\tww_dev/python/plugins\teksi_wastewater\tools\twwmaptools.py", line 312, in findPath
    self.appendProfile(vertices, edges)
  File "C:\Users/%usr%/AppData/Roaming/QGIS/QGIS3\profiles\tww_dev/python/plugins\teksi_wastewater\tools\twwmaptools.py", line 405, in appendProfile
    elem = TwwProfileSpecialStructureElement(
  File "C:\Users/%usr%/AppData/Roaming/QGIS/QGIS3\profiles\tww_dev/python/plugins\teksi_wastewater\tools\twwprofile.py", line 308, in __init__
    TwwProfileEdgeElement.__init__(
  File "C:\Users/%usr%/AppData/Roaming/QGIS/QGIS3\profiles\tww_dev/python/plugins\teksi_wastewater\tools\twwprofile.py", line 90, in __init__
    self.addSegment(
  File "C:\Users/%usr%/AppData/Roaming/QGIS/QGIS3\profiles\tww_dev/python/plugins\teksi_wastewater\tools\twwprofile.py", line 385, in addSegment
    self.detailGeometry = node_cache.attrAsGeometry(
  File "C:\Users/%usr%/AppData/Roaming/QGIS/QGIS3\profiles\tww_dev/python/plugins\teksi_wastewater\tools\twwnetwork.py", line 436, in attrAsGeometry
    m = re.search("(.*;)?(.*)", ewktstring)
  File "C:\OSGeo4W\apps\Python39\lib\re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Desktop (please complete the following information):**
 - TEKSI plugin version: dev
 - TEKSI datamodel version: dev
 - TEKSI project file version: 2024_01_15
 - QGIS Version - see the About menu: 3.28.11
 - Postgres: 12.17
 - Postgis: POSTGIS="3.0.0 r17983" [EXTENSION] PGSQL="120" GEOS="3.8.0-CAPI-1.13.1 " PROJ="6.3.1" LIBXML="2.9.4" LIBJSON="0.13.1" LIBPROTOBUF="1.3.3" WAGYU="0.4.3 (Internal)"
 - OS: Windows
 

**Additional context**

- The tww log shows `CRITICAL    Unknown field backflow_level`. Renaming backflow_level to backflow_level_current solves this part, but the problem remains
- The field backflow_level was renamed backflow_level_current on tww_od.wastewater_node
- The behaviour is the same backflow_level_current is null or not

**Comment by sjib** [comment]
- [ ] integrate small bug fixes as provided above backflow_level was renamed backflow_level_current @3nids 
- [ ] @urskaufmann - Network following has problems on qgep also. Issue raised for this xxx

if not disable it so it does not show up as button
- [ ] suggestion to move away from networkx implementation - current problems it is slow, alternative move to database instead and/or use new QGIS tools @ponceta starts new feature and refactoring process (get user inputs for refactoring also @urskaufmann )

**Comment by 3nids** [comment]
profile tool has been disabled
